services:
  router:
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    container_name: composed-haproxy
    image: haproxy:lts-alpine
    init: true
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    pull_policy: always
    read_only: true
    restart: on-failure
    ulimits:
      nproc: 16384
      nofile:
        soft: 16384
        hard: 16384
      memlock:
        soft: 8192
        hard: 16384
    volumes:
      - type: bind
        source: haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
        read_only: true
      - type: bind
        source: ffdhe2048.txt
        target: /usr/local/etc/haproxy/dhparam.pem
        read_only: true
  mtg:
    build: ./mtg/
    cap_drop:
      - ALL
    container_name: composed-mtg
    depends_on:
      - router
    # image: ghcr.io/9seconds/mtg:2
    init: true
    pull_policy: always
    restart: on-failure
    ulimits:
      nproc: 16384
      nofile:
        soft: 16384
        hard: 16384
      memlock:
        soft: 8192
        hard: 16384
    volumes:
      - type: bind
        source: mtg.toml
        target: /config.toml
        read_only: true
